CREATE DATABASE M_SSolve;
USE M_SSolve;

CREATE TABLE Funcionarios(
IdFuncionario INT PRIMARY KEY IDENTITY
,Nome VARCHAR(255) NOT NULL
,Salario FLOAT NOT NULL
);

CREATE TABLE Comodos(
IdComodo INT PRIMARY KEY IDENTITY
,Comodo VARCHAR(255) NOT NULL
);

CREATE TABLE Aparelhos(
IdAparelho INT PRIMARY KEY IDENTITY
,IdComodo INT FOREIGN KEY REFERENCES Comodos(IdComodo)
,Aparelho VARCHAR(255) NOT NULL
);

CREATE TABLE Clientes(
CNPJ CHAR(14) PRIMARY KEY NOT NULL
,NomeFantasia VARCHAR(255) NOT NULL
,RazaoSocial VARCHAR(255) NOT NULL
,Endereco VARCHAR(255) NOT NULL
);

CREATE TABLE Servicos(
IdServico INT PRIMARY KEY IDENTITY
,CNPJ CHAR(14) FOREIGN KEY REFERENCES Clientes(CNPJ)
,IdAparelho INT FOREIGN KEY REFERENCES Aparelhos(IdAparelho)
,Descricao TEXT
,DataDeInicio DATE NOT NULL
,DataDeConclusao DATE
,Preco FLOAT NOT NULL
,Status BIT NOT NULL DEFAULT(0)
);

CREATE TABLE FuncionariosServicos(
IdFuncionario INT FOREIGN KEY REFERENCES Funcionarios(IdFuncionario)
,IdServico INT FOREIGN KEY REFERENCES Servicos(IdServico)
);